# all the containers run in a same network by default in docker compose
version: '3.6'
services:
  postgres:
    image: postgres:13
    ports:
      - '5433:5432' # expose pg on port 5632 to not collide with pg from elswhere
    restart: always
    volumes:
      - db_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: spacex
      POSTGRES_HOST_AUTH_METHOD: trust
      POSTGRES_DB: ezsplit

  server:
    build: .
    ports:
      - '8080:8080'
    restart: always
    depends_on:
      - postgres
    environment:
      NODE_ENV: production
      DATABASE_URL: postgres://postgres:spacex@postgres:5433/ezsplit
      DATABASE_PASSWORD: spacex
      DATABASE_PORT: 5433
      DATABASE_USER: postgres
      DATABASE_NAME: ezsplit

volumes:
  db_data:
